# Generated by Django 4.1 on 2023-07-15 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=500)),
                (
                    "precio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=40, null=True
                    ),
                ),
                ("fecha_alta", models.DateTimeField(auto_now=True)),
                (
                    "archivos",
                    models.FileField(
                        default="archivos/terminos_y_Condiciones_registro.pdf",
                        max_length=300,
                        upload_to="archivos/",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Solicitudes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("descripcion", models.CharField(max_length=600)),
                ("ubicacion", models.CharField(max_length=100)),
                ("fecha_alta", models.DateTimeField(auto_now=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=200)),
                ("fecha_registro", models.DateTimeField(auto_now=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
    ]
