# Generated by Django 4.1 on 2023-08-04 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appRequest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudes",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fk_solicitudes_usuario",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario",
            ),
        ),
    ]
