# Generated by Django 4.1 on 2023-08-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appRequest", "0003_seguimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudes",
            name="status",
            field=models.CharField(default="Enviada", max_length=100),
        ),
    ]
